/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define if should build with MINC 2.0 */
#define MINC2 1

/* Name of package */
#define PACKAGE "mincmorph"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "Andrew Janke <rotor@cmr.uq.edu.au>"

/* Define to the full name of this package. */
#define PACKAGE_NAME "mincmorph"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "mincmorph 1.4"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "mincmorph"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.4"

/* Version number of package */
#define VERSION "1.4"
